# This workflow runs actions to pull, build, and run tacent unit tests.

name: Unit Tests

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # The buildtestwindows job builds and runs unit tests on windows.
  buildtestwindows:
    # The type of runner that the job will run on
    runs-on: windows-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v2

    # Runs a single command using the runners shell
    # - name: Run a one-line script
    #   run: echo Hello, world!

    # Runs a set of commands using the runners shell
    # - name: Run a multi-line script
    #   run: |
    #     echo Add other actions to build,
    #     echo test, and deploy your project.
      
    # Use CMake and NMake
    - uses: actions/checkout@master
    - uses: ilammy/msvc-dev-cmd@v1.2.0
    - name: Build using CMake NMake
      run: |
        echo '*** Configuring CMake ***'
        mkdir buildnmake
        cd buildnmake
        cmake .. -DCMAKE_BUILD_TYPE=Release -G "NMake Makefiles"
        echo '*** NMake Build ***'
        nmake install
        echo '*** Done Building ***'
    
#    - name: Unit Tests
#      run: |
#        echo 'Running Unit Tests'
#        cd UnitTests
#        .\UnitTests.exe
#        echo 'Done Running Unit Tests'

  # The buildtestubuntu job builds tacent on ubuntu.
  buildtestubuntu:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: seanmiddleditch/gha-setup-ninja@master
    - name: Build Using CMake Ninja
      run: |
        echo '*** Configuring CMake ***'
        mkdir buildninja
        cd buildninja
        cmake .. -GNinja -DCMAKE_BUILD_TYPE=Release -DCMAKE_CXX_COMPILER=clang -DCMAKE_C_COMPILER=clang
        echo '*** Ninja Build ***'
        ninja -v install
        echo '*** Done Building ***'

#    - name: Unit Tests
#      run: |
#        echo 'Running Unit Tests'
#        cd UnitTests
#        ./UnitTests
#        echo 'Done Running Unit Tests'
