# This workflow runs actions to pull, build, and run tacent unit tests.

name: Unit Tests

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # The buildrunwindows job builds and runs unit tests on windows.
  checkoutbuildrunwindows:
    # The type of runner that the job will run on
    runs-on: windows-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v2

    # Runs a single command using the runners shell
    # - name: Run a one-line script
    #   run: echo Hello, world!

    # Runs a set of commands using the runners shell
    # - name: Run a multi-line script
    #   run: |
    #     echo Add other actions to build,
    #     echo test, and deploy your project.
      
    # Use CMake and Ninja
    - uses: actions/checkout@master
    - uses: seanmiddleditch/gha-setup-ninja@master
    - uses: ilammy/msvc-dev-cmd@v1.2.0
    - name: Build CMake Ninja
      run: |
        # cd "C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\MSBuild\Current\Bin\"
        # .\MSBuild.exe $Env:GITHUB_WORKSPACE\UnitTests\Windows\UnitTests.sln
        # dir
        echo '*** Configuring CMake ***'
        mkdir buildninja
        cd buildninja
        cmake .. -DCMAKE_BUILD_TYPE=Release -G Ninja
        echo '*** Ninja Build ***'
        ninja install
        # & 'C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\MSBuild\Current\Bin\MSBuild.exe' $Env:GITHUB_WORKSPACE\UnitTests\Windows\UnitTests.sln
        echo '*** Done Building ***'
    
#    - name: Unit Tests
#      run: |
#        echo 'Running Unit Tests'
#        cd UnitTests
#        .\UnitTests.exe
#        echo 'Done Running Unit Tests'

  # The checkoutbuildrunubuntu job builds tacittexview on ubuntu.
  checkoutbuildrunubuntu:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Build Using Make
      run: |
        echo '*** Configuring CMake ***'
        #mkdir buildninja
        #cd buildninja
        #cmake .. -DCMAKE_BUILD_TYPE=Release -GNinja
        echo '*** Ninja Build ***'
        #ninja install
        echo '*** Done Building ***'
#
#        echo 'Build Using Make'
#        ./UnitTests/Linux/fixup_makefiles_for_github_runner.sh
#        cd UnitTests/Linux
#        make All
#        echo 'Done Build Using Make'
#    - name: Unit Tests
#      run: |
#        echo 'Running Unit Tests'
#        cd UnitTests
#        ./UnitTests
#        echo 'Done Running Unit Tests'
